version: "3.9"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  go_dump1090_exporter:
    image: marvinmartian/go_dump1090_exporter
    container_name: go_dump1090
    # volumes:
    #   - /run/dump1090-fa/:/run/dump1090-fa/ #uncomment if running on same host and want to read files directly (will need to change DUMP1090_path to /run/dump1090-fa/)
    expose:
      - 8000
    command: go_dump1090_exporter --port 8000 --path ${DUMP1090_PATH}
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=500d'
      - '--web.enable-lifecycle'
    depends_on:
      - go_dump1090_exporter
    restart: unless-stopped
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000