global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'go_dump1090'
    static_configs:
      - targets: ['go_dump1090_exporter:8000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']